version: "3.7"
services:
  django:
    container_name: smerge_daphne
    build:
      context: .
      dockerfile: Dockerfile.daphne
    image: daphne_docker
    stdin_open: true
    tty: true
    volumes:
      - ./snapmerge/media:/app/snapmerge/media
      - ./snapmerge/database:/app/snapmerge/database
    expose:
      - "8000"
  react_ext:
    container_name: smerge_ext
    build:
      context: .
      dockerfile: Dockerfile.react.ext.depl
    image: react_ext_docker
    stdin_open: true
    tty: true
    expose:
      - "5069"
  nginx:
    image: nginx:latest
    volumes:
      - ./data/nginx_deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./snapmerge/static:/static
      - ./secrets/rasp_certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    volumes:
      - ./secrets/rasp_certs:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email your.email@example.com --agree-tos -d idpsmerge.duckdns.org
    depends_on:
      - nginx
