version: "3.7"
services:
  django:
    container_name: smerge_server_access
    build:
      context: .
      dockerfile: Dockerfile.access
    image: smerge_docker
    stdin_open: true
    tty: true
    volumes:
      - ./snapmerge/media:/var/www/snapmerge/snapmerge/media
      - ./snapmerge/database:/var/www/snapmerge/snapmerge/database
      - ./Access_Portal/Web_Api/instance:/app/Access_Portal/Web_Api/instance
    ports:
      - "80:80"
      - "443:443"

  # redis:
  #   image: "redis:alpine"


  # certbot:
  #   image: certbot/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot